---
layout: post
author: 166yuan
titile: es6 promise 学习笔记
category: javascript
tag: promise
---

所谓Promise，就是一个对象，用来传递异步操作的消息。它代表了某个未来才会知道结果的事件（通常是一个异步操作），并且这个事件提供统一的API，可供进一步处理。

```Promise```对象有以下两个特点。

1.对象不受外界影响。
```Promise```有三种状态 ```Pending```(进行中)、```Resolve```(已完成)和```Reject```(已失败)
只有异步操作的结果，能够决定状态的改变，其它所有操作均不能。

2.一旦状态改变，就不会再变，任何时候都可以得到这个结果
Promise对象的改变有两种状态：从```Pending```变为```Resolved```和从```Pending```变为```Rejected```
和一般对象事件不同，一旦发生了。状态就不会再改变，会一直保持结果。即使你再添加，也会立即得到这个结果。

```Promise```也有一些缺点。首先，无法取消```Promise```，一旦新建它就会立即执行，无法中途取消。其次，如果不设置回调函数，Promise内部抛出的错误，不会反应到外部。第三，当处于```Pending```状态时，无法得知目前进展到哪一个阶段（刚刚开始还是即将完成）。

```Promise```用法

Promise构造函数
	传递一个包含成功与失败两个状态的函数，由js提供，不用我们操心

	var promise = new Promise(function(resolve, reject) {
	  // ... 这里可以执行我们的代码。比如ajax请求

	  if (/* 异步操作成功 */){
	    resolve(value);
	  } else {
	    reject(error);
	  }
	});

定义完```promise```后，就可以用```then```进行使用了。

	promise.then(function(value) {
	  // success
	}, function(error) {
	  // failure
	});

用```promise```来实现ajax

	var getJSON = function(url) {
	  var promise = new Promise(function(resolve, reject){
	    var client = new XMLHttpRequest();
	    client.open("GET", url);
	    client.onreadystatechange = handler;
	    client.responseType = "json";
	    client.setRequestHeader("Accept", "application/json");
	    client.send();

	    function handler() {
	      if (this.status === 200) {
	        resolve(this.response);
	      } else {
	        reject(new Error(this.statusText));
	      }
	    };
	  });

	  return promise;
	};

	getJSON("/posts.json").then(function(json) {
	  console.log('Contents: ' + json);
	}, function(error) {
	  console.error('出错了', error);
	});

promise也可以用另外一个promise对象来调用

	var pa = new Promise(function(resolve,reject){
		
	});

	var pb = new Promise(function(resolve,reject){
		resolve(pa);
	});

注意，这时pa的状态就会传递给pb，也就是说，pa的状态决定了pb的状态。如果pa的状态是Pending，那么pb的回调函数就会等待pa的状态改变；如果pa的状态已经是Resolved或者Rejected，那么pb的回调函数将会立刻执行。这样一个顺序执行的代码就悄然而生了。

###### promise 的精髓在于then

then方法返回的是一个新的Promise实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即then方法后面再调用另一个then方法。

then返回的是一个新的```Promise```对象,基于这点。我们可以进行链式调用

	var promise = new Promise(function(resolve,reject){
		var isok = true;
		if (isok) {
			resolve("success");
		}else{
			reject(new Error("failure"));
		}
	});

	promise.then(function(data){
		console.log(data);  //success
		return "haha";
	}).then(function(data){
		console.log(data); //haha
	});

调用的结果，由上一个promise的返回值决定。所以，一个更优雅的顺序执行代码就这样ok了。

##### Promise.prototype.catch()
Promise.prototype.catch方法是```.then(null, rejection)```的别名，用于指定发生错误时的回调函数。

	getJSON("/posts.json").then(function(posts) {
	  // ...
	}).catch(function(error) {
	  // 处理前一个回调函数运行时发生的错误
	  console.log('发生错误！', error);
	});

如果，promise的状态已改为resolved，则改变是无效的

	var promise = new Promise(function(resolve, reject) {
	  resolve("ok");
	  throw new Error('test');
	});
	promise
	  .then(function(value) { console.log(value) })
	  .catch(function(error) { console.log(error) });
	// ok

```Promise```对象的错误具有“冒泡”性质，会一直向后传递，直到被捕获为止。也就是说，错误总是会被下一个catch语句捕获。

跟传统的try/catch代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise对象抛出的错误不会传递到外层代码，即不会有任何反应。

### Promise.resolve()和Promise.reject()

将现有对象转为Promise对象，Promise.resolve和Promise.reject方法就起到这个作用

### Promise 与generator使用。完整实现同步运行。
	function getFoo () {
	  return new Promise(function (resolve, reject){
	    resolve('foo');
	  });
	}

	var g = function* () {
	  try {
	    var foo = yield getFoo();
	    console.log(foo);
	  } catch (e) {
	    console.log(e);
	  }
	};

	function run (generator) {
	  var it = generator();

	  function go(result) {  //generator使用
	    if (result.done) return result.value;

	    return result.value.then(function (value) {
	      return go(it.next(value));
	    }, function (error) {
	      return go(it.throw(value));
	    });
	  }

	  go(it.next());
	}

	run(g);


笔记来自```阮一峰```大神的 [ECMAcript6 入门](http://es6.ruanyifeng.com/)